function x3d_save(frag, file_name, time=0)

    ## Copyright (C) 2017, Bruce Minaker
    ## x3d_save.jl is free software you can redistribute it and/or modify it
    ## under the terms of the GNU General Public License as published by
    ## the Free Software Foundation either version 2, or (at your option)
    ## any later version.
    ##
    ## x3d_save.jl is distributed in the hope that it will be useful, but
    ## WITHOUT ANY WARRANTY without even the implied warranty of
    ## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    ## General Public License for more details at www.gnu.org/copyleft/gpl.html.
    ##
    ##--------------------------------------------------------------------

    ## This file creates the animated x3d file of the system

    s = """
<html>
<head>
<meta http-equiv='X-UA-Compatible'/>
<script type='text/javascript' src='https://www.x3dom.org/download/x3dom.js'> </script>
<link rel='stylesheet' type='text/css' href='https://www.x3dom.org/download/x3dom.css'/>
</head>
<body>
<p>Animation generated by EoM</p>
<x3d width='1900px' height='850px'>
<Scene>
<Background groundAngle='1.571' groundColor='0 0.3 0, 0 0.2 0' skyAngle='1.571' skyColor='0 0 0.5, 0.5 0.5 1'> </Background>
<Transform rotation='1 0 0 -1.571'>
<Group DEF='axis'>
 <Transform translation='0 0 0.100' rotation='1 0 0 1.571'>
  <Shape DEF='cone'>
   <Cone height='0.025'  bottomRadius='0.005'></Cone>
   <Appearance DEF='blue'>
     <Material diffuseColor='0.0 0.0 0.5' emissiveColor='0.0 0.0 0.5'></Material>
   </Appearance>
  </Shape>
 </Transform>
 <Transform translation='0 0.100 0'>
  <Shape USE='cone'></Shape>
 </Transform>
 <Transform translation='0.100 0 0' rotation='0 0 1 -1.571'>
  <Shape USE='cone'></Shape>
 </Transform>
 <Transform translation='0 0 0.050' rotation='1 0 0 1.571'>
  <Shape DEF='cyl'>
   <Cylinder height='0.090'  radius='0.0025'></Cylinder>
   <Appearance USE='blue'></Appearance>
  </Shape>
 </Transform>
 <Transform translation='0 0.050 0'>
  <Shape USE='cyl'></Shape>
 </Transform>
 <Transform translation='0.050 0 0' rotation='0 0 1 -1.571'>
  <Shape USE='cyl'></Shape>
 </Transform>
</Group>
"""
    if time > 0
        s *= "<TimeSensor DEF='IDtimer' loop='true' cycleInterval='$(time)'></TimeSensor>\n"
    end
    s *= """
$(frag)
</Transform>
</Scene>
</x3d>
</body>
</html>
"""
    open(file_name, "w") do file
        write(file, s)
    end
end
