function x3d_save(frag, file_name, time = 0)

## Copyright (C) 2017, Bruce Minaker
## x3d_save.jl is free software you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by
## the Free Software Foundation either version 2, or (at your option)
## any later version.
##
## x3d_save.jl is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details at www.gnu.org/copyleft/gpl.html.
##
##--------------------------------------------------------------------

## This file creates the animated x3d file of the system

    file = open(file_name, "w")

    println(file,"<html>\n<head>\n<meta http-equiv='X-UA-Compatible'/>")
    println(file,"<script type='text/javascript' src='https://www.x3dom.org/download/x3dom.js'> </script>")
    println(file,"<link rel='stylesheet' type='text/css' href='https://www.x3dom.org/download/x3dom.css'/>")
    println(file,"</head>\n<body>")
    println(file,"<p>Animation generated by EoM</p>")
    println(file,"<x3d width='1900px' height='850px'>")
    println(file,"<Scene>")
    println(file,"<Background groundAngle='1.571' groundColor='0 0.3 0, 0 0.2 0' skyAngle='1.571' skyColor='0 0 0.5, 0.5 0.5 1'> </Background>")  ## sky and ground background

    println(file,"<Transform rotation='1 0 0 -1.571'>")  ##  Rotate the entire world to put z up
    println(file,"<Group DEF='axis'>")  ## Generate the arrows at the origin
    println(file," <Transform translation='0 0 0.100' rotation='1 0 0 1.571'>")
    println(file,"  <Shape DEF='cone'>")
    println(file,"   <Cone height='0.025'  bottomRadius='0.005'></Cone>")
    println(file,"   <Appearance DEF='blue'>")
    println(file,"     <Material diffuseColor='0.0 0.0 0.5' emissiveColor='0.0 0.0 0.5'></Material>")
    println(file,"   </Appearance>")
    println(file,"  </Shape>")
    println(file," </Transform>")

    println(file," <Transform translation='0 0.100 0'>")
    println(file,"  <Shape USE='cone'></Shape>")
    println(file," </Transform>")

    println(file," <Transform translation='0.100 0 0' rotation='0 0 1 -1.571'>")
    println(file,"  <Shape USE='cone'></Shape>")
    println(file," </Transform>")

    println(file," <Transform translation='0 0 0.050' rotation='1 0 0 1.571'>")
    println(file,"  <Shape DEF='cyl'>")
    println(file,"   <Cylinder height='0.090'  radius='0.0025'></Cylinder>")
    println(file,"   <Appearance USE='blue'></Appearance>")
    println(file,"  </Shape>")
    println(file," </Transform>")

    println(file," <Transform translation='0 0.050 0'>")
    println(file,"  <Shape USE='cyl'></Shape>")
    println(file," </Transform>")

    println(file," <Transform translation='0.050 0 0' rotation='0 0 1 -1.571'>")
    println(file,"  <Shape USE='cyl'></Shape>")
    println(file," </Transform>")

    println(file,"</Group>") ## End of axis arrows

    if time > 0
        println(file,"<TimeSensor DEF='IDtimer' loop='true' cycleInterval='",time,"'></TimeSensor>")  ## At the loop timer for the animations
    end
    
    println(file,frag)  ## Insert the incoming x3d content

    println(file,"</Transform>")  ## End of world rotation
    println(file,"</Scene>")  ## End of x3d
    println(file,"</x3d>\n</body>\n</html>")

    close(file)

end
